### PR TITLE
Added support for PDFreactor 11

### LINKED ISSUE #22: [PDFReactor] enableDebugMode is deprecated
https://www.pdfreactor.com/resources/10.2.10722/doc/webservice/web-service-client.html#Configuration-enableDebugMode

Should refactor the `enableDebugMode`, potentially need to apply the change on 10.6 too.

### PR DESCRIPTION
**Pull request by fashxp**
fixes https://github.com/pimcore/web-to-print-bundle/issues/22

alternative for https://github.com/pimcore/web-to-print-bundle/pull/88

### CODE REVIEW

**Comment by AlternateIf** [comment]
@fashxp 
is this forcing version 12 of pdfreactor?
https://github.com/pimcore/web-to-print-bundle/blob/support-pdfreactor-11/src/Processor/Api/PDFreactor.class.php#L779

i tried using this for a v11 pdfreactor and got a
"Invalid client data. Cannot deserialize value of type `int` from String "12.0.0": not a valid `int` value"

When changing the const to a int 
    public const VERSION = 12;
 it seems to work for my pdfreactor 11

**Comment by fashxp** [comment]
Hmm, should not, will check with pdfreactor guys. Thx for reporting...

**Comment by fashxp** [comment]
@AlternateIf could you please double check if the latest changes work for you?

**Comment by fashxp** [comment]
@AlternateIf I'll merge it for now ... if there remain some problems we need to address this in followup PRs.

**Pull request merged**
