### PR TITLE
PDF download route renamed

### LINKED ISSUE #52: PDF download
When downloading document the error is shown:
image

Seems like route name [pimcore_bundle_document_printpage_pdfdownload](https://github.com/pimcore/web-to-print-bundle/blob/4f46683fff81c6b88d537251a47d6da107a98720/public/js/document/printpages/pdf_preview.js#L95C80-L95C80) doesn't match routing list

image

### PR DESCRIPTION
**Pull request by JasminBektic**

### CODE REVIEW

**Review by kingjia90 — APPROVED** [review]
Thank you for the fix!

Waiting for CLA assistant fix from our side and would be merged

**Comment by bluvulture** [comment]
hey @kingjia90  @JasminBektic 

@JasminBektic could you please sign cla as the cla check is working now ? 

Tnx

**Comment by Cruiser13** [comment]
@kingjia90 any chance to get new releases 1.1.1 and 1.2.0?

**Comment by kingjia90** [comment]
@Cruiser13 sure, i will make a request (new internal guidelines) for it, at least 1.1.1 should be released soon

**Pull request merged**
