### PR TITLE
[Bug] Fix no result

### PR DESCRIPTION
**Pull request by mattamon**
Codeception fails if no result is obtained due to trying to access property on null.
https://github.com/pimcore/web-to-print-bundle/actions/runs/11472288862/job/31924629146

### CODE REVIEW

**Comment by kingjia90** [comment]
Thank you for fixing the tests, however i believe it is not fixing the underlying issue which seems caused by a BC BREAK from the release of PDFReactor [v12](https://www.pdfreactor.com/product/changelog.htm) on 16th October (the exact date when it started the series of not passing the tests).


image

**Comment by kingjia90** [comment]
Maybe related to https://github.com/pimcore/web-to-print-bundle/issues/22

**Comment by mattamon** [comment]
> Thank you for fixing the tests, however i believe it is not fixing the underlying issue which seems caused by a BC BREAK from the release of PDFReactor [v12](https://www.pdfreactor.com/product/changelog.htm) on 16th October (the exact date when it started the series of not passing the tests).
> 
> image

Question is, if we can fix it without a BC-Break ourselves?

**Comment by kingjia90** [comment]
Good question 🤔  
If we rely on their cloud service, we(and devs,partners) have no other choices other than to adapt to it, as they do not seem to provide a sort of LTS or versioning for the APIs
https://github.com/pimcore/web-to-print-bundle/blob/d18a09bc07179b3bc14dc6e923dd1fdb793c6841/tests/Model/Config/ConfigTest.php#L29

It could be also that they had an unintentional regression and may be fixed soon

**Comment by mattamon** [comment]
> Good question 🤔  
> If we rely on their cloud service, we(and devs,partners) have no other choices other than to adapt to it, as they do not seem to provide a sort of LTS or versioning for the APIs
> https://github.com/pimcore/web-to-print-bundle/blob/d18a09bc07179b3bc14dc6e923dd1fdb793c6841/tests/Model/Config/ConfigTest.php#L29
> 
> It could be also that they had an unintentional regression and may be fixed soon

Could this also be a license problem?
https://www.pdfreactor.com/pricing/ seems like you need to buy it and have an apikey?

**Comment by fashxp** [comment]
I'm in contact with realobjects. As @kingjia90 suspected, this behavior is a result of their new major release PDFreactor 12 ... which returns errors when configuration is invalid/wrong. 
Currently checking, what we can do and what versions we can support in parallel.

**Comment by fashxp** [comment]
alternative approach see https://github.com/pimcore/web-to-print-bundle/pull/89

**Comment by mattamon** [comment]
Closing in favor of #89

**Pull request closed without merging**
